// @ts-check
import { serializeVault } from '../js/services/export.js';
import { parseHTML } from '../js/services/import.js';
import { parseText } from '../js/workers/import-parser.worker.js';
import { createZip, crc32 } from './zip.js';
import { VirtualList } from '../js/core/virtual-list.js';
/** Additional release tests. @param {object} context */
export async function runReleaseTests({test,assert,equal,waitFor,delay,frame,doc,navigate,click,vault,refresh}) {
  await test('JSON backup serialization preserves notes, tags and bookmark fields',()=>{const output=serializeVault(vault.value,'json');const decoded=JSON.parse(output.content);equal(decoded.bookmarks,vault.value.bookmarks);equal(decoded.tags,vault.value.tags);equal(decoded.version,1);});
  await test('HTML export round-trips active bookmarks and escapes markup',()=>{const data={bookmarks:[{url:'https://example.org/export?a=1&b=2',title:'A <b>title</b> & "quotes"',createdAt:1700000000000,folderId:'folder',tagIds:[],deletedAt:null}],folders:[{id:'folder',name:'A & B',parentId:null}],tags:[]};const exported=serializeVault(data,'html');assert(!exported.content.includes('<b>title</b>'));const imported=parseHTML(exported.content);equal(imported.bookmarks.length,1);equal(imported.bookmarks[0].title,data.bookmarks[0].title);equal(imported.folders[0].name,'A & B');});
  await test('CSV export round-trips quotes, commas and description newlines',()=>{const record={url:'https://example.org/csv',title:'A, "quoted" title',description:'Line one\nLine two',createdAt:1700000000000,tagIds:[],deletedAt:null};const parsed=parseText(serializeVault({bookmarks:[record],folders:[],tags:[]},'csv').content,'csv');equal(parsed.bookmarks[0].title,record.title);equal(parsed.bookmarks[0].description,record.description);});
  await test('5,000-item windowing keeps DOM bounded and reaches the final item',()=>{const host=document.createElement('div');host.className='release-test-viewport';document.body.append(host);const items=Array.from({length:5000},(_,i)=>({id:String(i),title:`Test-only row ${i}`}));const list=new VirtualList(host,item=>{const node=document.createElement('article');node.className='release-test-row';node.tabIndex=0;node.textContent=item.title;return node;});try{list.setItems(items,'list');assert(host.querySelectorAll('[role=listitem]').length<100);list.scrollToIndex(4999);assert(host.querySelector('[data-key="4999"]'));equal(host.querySelector('[data-key="4999"]').getAttribute('aria-setsize'),'5000');assert(host.querySelectorAll('[role=listitem]').length<100);}finally{list.destroy();host.remove();}});
  await test('Virtual list preserves keyed focus during data updates',()=>{const host=document.createElement('div');host.className='release-test-viewport';document.body.append(host);const list=new VirtualList(host,item=>{const node=document.createElement('article');node.className='release-test-row';node.tabIndex=0;node.textContent=item.title;return node;});try{list.setItems([{id:'one',title:'Before'}],'list');const original=host.querySelector('[data-key]');original.focus();list.setItems([{id:'one',title:'After'}],'list');assert(original===host.querySelector('[data-key]'));assert(document.activeElement===original);equal(original.textContent,'After');}finally{list.destroy();host.remove();}});
  await test('Theme icons represent current dark/light state and repo links are wired',async()=>{await navigate('/');await waitFor(()=>doc().querySelector('.marketing-nav'),'marketing');const theme=doc().querySelector('.marketing-nav [data-action=theme]');if(doc().documentElement.dataset.theme!=='dark')theme.click();equal(theme.querySelector('mv-icon').getAttribute('name'),'moon');theme.click();await delay(60);equal(doc().documentElement.dataset.theme,'light');equal(theme.querySelector('mv-icon').getAttribute('name'),'sun');theme.click();assert(doc().querySelector('.github-button').href==='https://github.com/TajkirHossen-14/MarkVault');});
  await test('Footer no longer includes technology stack or a theme toggle',()=>{const footer=doc().querySelector('footer');assert(!footer.textContent.includes('Built with vanilla JavaScript'));assert(!footer.querySelector('[data-action=theme]'));assert(footer.querySelector('a[href="https://github.com/TajkirHossen-14/MarkVault/issues"]'));});
  await test('Navigation sheet has labelled icons, functional theme and close controls',async()=>{click('[data-action=menu]');await waitFor(()=>doc().querySelector('.marketing-menu[open]'),'navigation sheet');const menu=doc().querySelector('.marketing-menu');equal(menu.querySelectorAll('.mobile-menu-links a').length,5);equal(menu.querySelectorAll('.menu-link-icon mv-icon').length,5);menu.querySelector('[data-action=theme]').click();equal(menu.querySelector('[data-action=theme] mv-icon').getAttribute('name'),'sun');menu.querySelector('[data-action=theme]').click();menu.querySelector('[data-action=close]').click();await waitFor(()=>!doc().querySelector('dialog[open]')&&!doc().getElementById('root').inert,'native close event and inert cleanup');assert(!doc().getElementById('root').inert);});
  await test('Every hamburger section link navigates after close without focus scrolling back',async()=>{for(const id of ['features','shortcuts','privacy','faq']){click('[data-action=menu]');await waitFor(()=>doc().querySelector('.marketing-menu[open]'),'menu');click(`dialog [data-jump="${id}"] .menu-link-icon`);await waitFor(()=>!doc().querySelector('dialog[open]')&&!doc().getElementById('root').inert,'menu close');await waitFor(()=>Math.abs(doc().getElementById(id).getBoundingClientRect().top)<120,`destination ${id}`,5000);}click('[data-action=menu]');await waitFor(()=>doc().querySelector('.marketing-menu[open]'),'menu CTA');click('dialog .mobile-menu-bottom a[href="#/app"]');await waitFor(()=>doc().querySelector('.app-shell'),'Open MarkVault destination');});
  await test('Library hamburger links navigate to their actual smart-view routes',async()=>{for(const [route,title] of [['/app/unread','Unread'],['/app/favorites','Favorites'],['/app/trash','Trash']]){click('[data-action=mobile-menu]');await waitFor(()=>doc().querySelector('.app-mobile-dialog[open]'),'library menu');click(`dialog a[href="#${route}"]`);await waitFor(()=>frame.contentWindow.location.hash==='#'+route&&doc().querySelector('#view-title')?.textContent.includes(title),title+' destination');await waitFor(()=>!doc().querySelector('dialog[open]')&&!doc().getElementById('root').inert,'route unlocked');}await navigate('/app');});
  await test('App sidebar sheet closes without changing persisted collapse state',async()=>{await navigate('/app');await waitFor(()=>doc().querySelector('.app-shell'),'app');const collapsed=doc().querySelector('.app-shell').classList.contains('is-collapsed');click('[data-action=mobile-menu]');await waitFor(()=>doc().querySelector('.app-mobile-dialog[open]'),'app sheet');click('dialog [data-action=close-menu]');await waitFor(()=>!doc().querySelector('dialog[open]'),'sheet close');equal(doc().querySelector('.app-shell').classList.contains('is-collapsed'),collapsed);});
  await test('Bookmark survives a real browser document reload',async()=>{const loaded=new Promise(resolve=>frame.addEventListener('load',resolve,{once:true}));frame.contentWindow.location.reload();await loaded;await waitFor(()=>doc().querySelector('.bookmark-card,.bookmark-row'),'persisted bookmarks');await refresh();equal(vault.value.bookmarks.length,2);});
  await test('Desktop sidebar collapses to icons and can reopen from its visible rail toggle',async()=>{await navigate('/app');await waitFor(()=>doc().querySelector('.sidebar-brand [data-action=collapse]'),'sidebar');const shell=doc().querySelector('.app-shell');if(shell.classList.contains('is-collapsed'))click('.sidebar-brand [data-action=collapse]');click('.sidebar-brand [data-action=collapse]');await delay(280);assert(shell.classList.contains('is-collapsed'));const toggle=doc().querySelector('.sidebar-brand [data-action=collapse]');assert(frame.contentWindow.getComputedStyle(toggle).display!=='none');equal(toggle.getAttribute('aria-label'),'Expand sidebar');assert([...doc().querySelectorAll('.app-shell>.sidebar .sidebar-label')].every(el=>frame.contentWindow.getComputedStyle(el).display==='none'));click('.sidebar-brand [data-action=collapse]');await delay(280);assert(!shell.classList.contains('is-collapsed'));equal(toggle.getAttribute('aria-label'),'Collapse sidebar');});
  await test('Nav actions are ordered CTA, theme, GitHub and footer attribution has no icon',async()=>{await navigate('/');await waitFor(()=>doc().querySelector('.nav-actions'),'navigation');const actions=[...doc().querySelector('.nav-actions').children];assert(actions[0].classList.contains('nav-cta'));equal(actions[1].dataset.action,'theme');assert(actions[2].classList.contains('github-button'));assert(!doc().querySelector('.footer-source mv-icon'));});
  await test('Real source download screen builds a complete browser-only ZIP',async()=>{const loaded=new Promise(resolve=>frame.addEventListener('load',resolve,{once:true}));frame.src='../dev/download.html';await loaded;await waitFor(()=>doc().querySelector('#download-source'),'source download screen');click('#download-source');await waitFor(()=>doc().querySelector('#download-status')?.textContent.startsWith('Ready:'),'complete source ZIP',30000);assert(!doc().querySelector('#download-source').disabled);});
  let manifest,files=[];
  await test('Complete source inventory fetches successfully, including guides and fonts',async()=>{const response=await fetch('../source-manifest.json',{cache:'no-store'});assert(response.ok);manifest=await response.json();let cursor=0;await Promise.all(Array.from({length:6},async()=>{while(cursor<manifest.files.length){const name=manifest.files[cursor++];const response=await fetch('../'+name,{cache:'no-store'});assert(response.ok,`${name} returned ${response.status}`);files.push({name,data:new Uint8Array(await response.arrayBuffer())});}}));equal(files.length,manifest.files.length);assert(files.find(f=>f.name==='USER-GUIDE-BN.md'));assert(files.find(f=>f.name==='IDE-AI-HANDOFF.md'));});
  await test('Production uses one index.html entry and PWA starts on its library route',()=>{equal(manifest.files.filter(path=>path.endsWith('.html')&&!path.startsWith('dev/')),['index.html']);const pwa=JSON.parse(new TextDecoder().decode(files.find(file=>file.name==='manifest.webmanifest').data));equal(pwa.start_url,'./index.html#/app');assert(!manifest.files.includes('js/review-entry.js'));assert(!manifest.files.includes('ARCHITECTURE.md'));assert(!manifest.files.includes('TEST-REPORT.md'));});
  await test('ZIP encoder emits valid local headers, CRC32 values and central directory',async()=>{equal(crc32(new TextEncoder().encode('123456789')),0xcbf43926);const zip=createZip(files),data=new Uint8Array(await zip.arrayBuffer()),view=new DataView(data.buffer);equal(view.getUint32(0,true),0x04034b50);equal(view.getUint32(data.length-22,true),0x06054b50);equal(view.getUint16(data.length-12,true),files.length);let offset=0;for(const file of files){equal(view.getUint32(offset,true),0x04034b50);equal(view.getUint32(offset+14,true),crc32(file.data));equal(view.getUint32(offset+18,true),file.data.length);offset+=30+view.getUint16(offset+26,true)+file.data.length;}equal(view.getUint32(offset,true),0x02014b50);});
  await test('Service-worker precache covers all shipping app modules/styles/fonts',()=>{const source=new TextDecoder().decode(files.find(f=>f.name==='sw.js').data);const body=/const essentials = \[([^\]]+)\]/.exec(source)?.[1];assert(body,'Precache inventory missing');const paths=[...body.matchAll(/'([^']+)'/g)].map(m=>m[1]);for(const path of paths)assert(manifest.files.includes(path),`Unshipped cache path ${path}`);for(const path of manifest.files.filter(p=>p.startsWith('js/')||p.startsWith('css/')||p.endsWith('.woff2')))assert(paths.includes(path),`Missing offline cache asset ${path}`);});
  await test('All relative static ES-module imports resolve in the source inventory',()=>{const origin=new URL('../',location.href);for(const file of files.filter(f=>f.name.startsWith('js/')&&f.name.endsWith('.js'))){const text=new TextDecoder().decode(file.data);const pattern=/(?:from\s*|import\s*\(\s*|import\s*)['"](\.[^'"]+)['"]/g;for(const match of text.matchAll(pattern)){const resolved=new URL(match[1],new URL(file.name,origin));const relative=resolved.pathname.slice(origin.pathname.length);assert(manifest.files.includes(relative),`${file.name} imports missing ${relative}`);}}});
}
