// @ts-check
import { html } from '../core/dom.js';
import { shortcuts } from '../lib/constants.js';
const sections = [
['getting-started','A small tool. A good place to start.','Open your vault and save a link with New bookmark, or press N. New vaults are truly empty. Add folders for structure and comma-separated tags for connections. Your bookmarks stay in this browser at this site address.','All, Unread, Favorites, Recent, Unreachable, and Trash offer different paths back into your collection. Search matches titles, domains, URLs, notes, and tags.'],
['import','Bring your collection along.','In Chrome or Edge, use the bookmark manager menu → Export bookmarks. In Firefox: Library → Import and Backup → Export Bookmarks to HTML. In Safari: File → Export → Bookmarks.','Choose Import in MarkVault, select your HTML, JSON, or CSV file, review the preview, then confirm. Invalid links are excluded; normalized duplicate URLs are skipped, including those in Trash. Browser folders beyond three levels are flattened.'],
['export','Leave the door open.','JSON is the best backup: it keeps notes, tags, folders, timestamps, visits, and Trash. HTML preserves active bookmarks and folder structure for browser import. CSV is useful for spreadsheets and other tools.','Import merges rather than overwrites. Existing duplicate URLs are left unchanged. To restore all exported bookmark data, import into an empty vault. Preferences, cached previews, and original identifiers are not restored.'],
['backups','Your data deserves a second copy.','MarkVault stores data in IndexedDB on this device. There is no sync server or recovery account. Clearing site data or deleting your browser profile can remove your vault. Private-mode sessions may be temporary.','Export JSON regularly and keep it outside the browser. Persistent storage reduces automatic eviction, not manual deletion. A new site domain or port has separate browser storage: export before moving.'],
['privacy','Private by architecture.','No analytics, tracking pixels, or background vault uploads. Code, icons, and fonts are served from this site. Multiple tabs synchronize locally with BroadcastChannel.','External favicons send domains to Google; optional previews send full URLs to your chosen provider. Both are off by default. Manual network checks and opening bookmarks connect to those websites. Requests to optional providers may fail or be rate-limited.'],
['sharing','Share a link, not your vault.','Select bookmarks and choose Share. URLs, titles, and descriptions are compressed directly into the share URL. Notes and visit history are excluded. Nothing is uploaded.','Anyone with that URL can decode its contents. Never share confidential URLs. Long links may be truncated by messaging apps. The recipient can explicitly import a copy.'],
['changelog','The first chapter.','Version 1.0 brings local bookmarks, folders, tags, search, three views, favorites, reading state, Trash, keyboard controls, import/export, sharing, settings, and insights.','Built with native ES modules, custom elements, browser APIs, and no runtime dependencies. Read the project README and test report for implementation scope and verified behavior.'],
['roadmap','Thoughtful next steps.','Remaining work includes a strict JavaScript type audit, full browser/accessibility testing, enhanced variable-height virtualization, and advanced folder drag-and-drop with edge auto-scroll.','No cloud sync, accounts, or collaboration server is included. Cross-device workflows use export/import. The source repository is github.com/TajkirHossen-14/MarkVault. Suggestions and reproducible bug reports are welcome through GitHub Issues.'],
['license','MIT licensed.','You may use, copy, modify, merge, publish, distribute, sublicense, and sell this software subject to retaining its copyright and permission notice.','Provided as is, without warranty. See LICENSE for the full text. Geist and JetBrains Mono use their respective SIL Open Font Licenses.'],
['support','A useful bug report goes a long way.','Export a backup before troubleshooting. Include your browser version, screen size, exact site URL, and reproduction steps. Never share confidential links or notes in public bug reports.','Report issues at github.com/TajkirHossen-14/MarkVault/issues. Download the source and read the Bengali user guide and IDE-AI handoff to continue developing locally.']
];
/** Documentation with real in-project destinations. @param {HTMLElement} root @param {URLSearchParams} params @param {object} context */
export function mount(root, params, { signal }) {
  root.append(html`<main class="docs-page" id="main-content"><header class="standalone-header"><a class="brand" href="#/"><img src="assets/icons/logo.svg" width="30" height="30" alt="">MarkVault</a><a class="btn btn-primary" href="#/app">Open your vault <mv-icon name="arrow"></mv-icon></a></header><div class="standalone-heading"><span class="eyebrow">THE MARKVAULT FIELD GUIDE</span><h1>A little guidance.<br>A lot of possibility.</h1><p>Everything you need to make yourself at home. No fine print.</p></div><nav class="doc-links" aria-label="Documentation sections">${sections.map(([id]) => html`<a href="#${id}" data-doc="${id}">${id[0].toUpperCase() + id.slice(1)}</a>`)}<a href="#keyboard" data-doc="keyboard">Keyboard reference</a><a href="dev/download.html">Download source</a><a href="https://github.com/TajkirHossen-14/MarkVault" target="_blank" rel="noopener noreferrer">GitHub repository</a><a href="https://github.com/TajkirHossen-14/MarkVault/issues" target="_blank" rel="noopener noreferrer">Report an issue</a></nav><div class="docs-content">${sections.map(([id,title,a,b]) => html`<section class="doc-section" id="doc-${id}"><h2>${title}</h2><p>${a}</p><p>${b}</p>${id === 'import' ? html`<a class="btn btn-primary" href="#/app?import=1">Import bookmarks <mv-icon name="upload"></mv-icon></a>` : ''}</section>`)}<section class="doc-section" id="doc-keyboard"><h2>A shortcut to everything.</h2>${shortcuts.map(s => html`<div class="shortcut-row"><span>${s.label}</span><kbd>${s.keys}</kbd></div>`)}</section></div></main>`);
  root.addEventListener('click', event => { const link = event.target.closest('[data-doc]'); if (link) { event.preventDefault(); root.querySelector(`#doc-${link.dataset.doc}`)?.scrollIntoView(); } }, { signal });
  const aliases = { 'how your data is stored':'privacy', 'third-party requests':'privacy', 'keyboard reference':'keyboard', shortcuts:'keyboard', 'license':'license', 'report an issue':'support', github:'roadmap', features:'getting-started', documentation:'getting-started', faq:'getting-started' };
  const topic = params.get('topic'); if (topic) { const id = aliases[topic] || topic; requestAnimationFrame(() => root.querySelector(`#doc-${CSS.escape(id)}`)?.scrollIntoView()); }
}
