// @ts-check
import { html, delegate } from '../core/dom.js';
import { applyTheme } from '../core/store.js';
import { showShortcuts, showInfo, showBookmark } from '../components/dialogs.js';
import { toast } from '../components/primitives.js';
/** Existing production primitives, not placeholder custom-element variants. @param {HTMLElement} root @param {URLSearchParams} params @param {object} context */
export function mount(root, params, { signal }) {
  root.append(html`<main class="docs-page" id="main-content"><header class="standalone-header"><a class="brand" href="#/">MarkVault / UI workshop</a><div class="flex"><button class="btn" data-action="dark">Dark</button><button class="btn" data-action="light">Light</button><a class="btn" href="dev/harness.html">Tests</a></div></header><div class="docs-content"><section class="doc-section"><h2>Buttons and states</h2><div class="flex"><button class="btn btn-primary" data-action="bookmark">Primary <mv-icon name="arrow"></mv-icon></button><button class="btn" data-action="dialog">Secondary</button><button class="btn btn-ghost" data-action="toast">Ghost</button><button class="btn" disabled>Disabled</button><button class="icon-btn" aria-label="Keyboard shortcuts" data-action="shortcuts"><mv-icon name="keyboard"></mv-icon></button></div></section><section class="doc-section"><h2>Input and selection</h2><div class="form-row"><label>Text input<input placeholder="Type something thoughtful"></label><label>Select<select><option>Comfortable</option><option>Compact</option></select></label></div><label class="check-label"><input type="checkbox">Native, accessible checkbox</label></section><section class="doc-section"><h2>Tags, icons, shortcuts</h2><div class="flex">${['ideas','design','reading','tools','inspiration'].map(label=>html`<mv-tag-pill label="${label}"></mv-tag-pill>`)}<mv-kbd keys="⌘ K"></mv-kbd></div><div class="flex">${['bookmark','folder','star','shield','upload','search'].map(name=>html`<mv-icon name="${name}"></mv-icon>`)}</div></section><section class="doc-section"><h2>Empty states</h2><mv-empty-state icon="inbox" heading="All caught up." description="Your next discovery starts with a single link."></mv-empty-state><div class="notice"><mv-icon name="shield"></mv-icon><p>Every surface uses the same design tokens. No browser-default surprise.</p></div></section></div></main>`);
  delegate(root, { dark:()=>applyTheme('dark'), light:()=>applyTheme('light'), dialog:()=>showInfo('A considered little dialog.','Native focus trapping, Escape to close, background inertness, and focus restoration.'), toast:()=>toast('A non-blocking, accessible notification.'), shortcuts:showShortcuts, bookmark:()=>showBookmark() }, signal);
}
