// @ts-check
import { html, delegate } from '../core/dom.js';
import { applyTheme } from '../core/store.js';
import { shortcuts } from '../lib/constants.js';
import { openDialog } from '../core/focus.js';
import { showShortcuts } from '../components/dialogs.js';
import { showMarketingMenu } from '../components/marketing-menu.js';
const repository = 'https://github.com/TajkirHossen-14/MarkVault';
const footerLink = label => label === 'GitHub' ? repository : label === 'Report an issue' ? `${repository}/issues` : label === 'License' ? `${repository}/blob/main/LICENSE` : `#/docs?topic=${encodeURIComponent(label.toLowerCase())}`;
const icon = name => html`<mv-icon name="${name}"></mv-icon>`;
const brand = () => html`<a class="brand" href="#/" aria-label="MarkVault home"><img src="assets/icons/logo.svg" width="36" height="36" alt="">MarkVault</a>`;
const features = [
  ['folder','A little structure. A lot of clarity.','Folders for the big picture. Tags for the little details. Everything in a place that makes sense to you.','organize'],
  ['search','Find the thought. Not the tab.','Fast, fuzzy search across titles, links, tags, and notes. A few letters are all it takes.','find'],
  ['shield','Yours. Actually yours.','Saved on your device, not someone else’s server. No account required.','private'],
  ['keyboard','Stay in your flow.','Your next action is a keystroke away.','keys'],
  ['upload','Bring your internet with you.','Import from your browser. Export whenever you like. No lock-in, ever.','portable'],
  ['moon','A calmer place to come back to.','Thoughtful details. Two beautiful themes. No distractions.','calm']
];
const faqs = [
  ['Where are my bookmarks stored?', 'Right here, in this browser’s IndexedDB storage. MarkVault does not have a server or an account system. Your vault belongs to this browser profile and this site address.'],
  ['Is MarkVault really free?', 'Yes. There are no subscriptions, premium tiers, account requirements, or artificial bookmark limits. The practical limit is your browser’s available storage.'],
  ['Can I bring bookmarks from my browser?', 'Absolutely. Export bookmarks as an HTML file from Chrome, Firefox, Safari, or Edge, then choose Import in MarkVault. You can preview the results before saving. MarkVault JSON and CSV files are also supported.'],
  ['Will my bookmarks sync across devices?', 'Not automatically. This is a truly local-first app, with no sync server. Export a JSON backup on one device and import it on another. Multiple MarkVault tabs in the same browser do stay in sync.'],
  ['What happens if I clear my browser data?', 'Clearing site data or deleting your browser profile can remove your vault. Export a JSON backup regularly and keep it somewhere safe. MarkVault includes backup reminders and can request persistent browser storage.'],
  ['Does anything leave my browser?', 'Nothing from your vault is sent anywhere by default. Optional favicons and link previews contact third-party services only after you enable them. Opening a bookmark or manually checking link health connects to that website.']
];
/** Complete marketing page; the product frame depicts a genuinely empty vault. @param {HTMLElement} root @param {URLSearchParams} params @param {object} context */
export function mount(root, params, { signal }) {
  root.append(html`
    <div class="nav-sentinel"></div>
    <header class="marketing-nav"><div class="nav-inner">${brand()}<nav class="nav-links" aria-label="Main navigation"><a href="#features" data-section="features">Features</a><a href="#shortcuts" data-section="shortcuts">Shortcuts</a><a href="#privacy" data-section="privacy">Privacy</a><a href="#faq" data-section="faq">FAQ</a></nav><div class="nav-actions"><a class="btn btn-primary btn-small nav-cta" href="#/app">Open MarkVault ${icon('arrow')}</a><button class="icon-btn" data-action="theme" aria-label="${document.documentElement.dataset.theme==='light'?'Light theme. Switch to dark.':'Dark theme. Switch to light.'}">${icon(document.documentElement.dataset.theme==='light'?'sun':'moon')}</button><a class="icon-btn github-button" href="${repository}" target="_blank" rel="noopener noreferrer" aria-label="MarkVault on GitHub">${icon('github')}</a><button class="icon-btn mobile-menu" data-action="menu" aria-label="Open navigation">${icon('menu')}</button></div></div></header>
    <main id="main-content">
      <section class="hero" aria-labelledby="hero-title"><div class="hero-grid"></div><div class="hero-content"><span class="hero-badge"><span class="status-dot"></span> Runs entirely in your browser <span class="badge-divider"></span>${icon('arrow')}</span><h1 id="hero-title">Your links,<br><span class="hero-accent">finally organized.</span></h1><p class="hero-description">A quiet home for everything worth keeping.<br>Save, sort, and rediscover your corner of the internet. All yours, all local.</p><div class="hero-actions"><a class="btn btn-primary hero-cta" href="#/app">Open MarkVault ${icon('arrow')}</a><a class="btn btn-ghost" href="#features" data-section="features">How it works ${icon('down')}</a></div><p class="hero-micro">No account. <span>No server.</span> No tracking.</p></div>
      <div class="product-stage"><div class="product-frame"><div class="browser-chrome"><div class="traffic-lights"><i></i><i></i><i></i></div><span class="browser-address">${icon('lock')} markvault / your space</span><span class="browser-local"><span class="status-dot"></span> Local-first</span></div><div class="preview-app"><aside class="preview-sidebar"><span class="brand"><img src="assets/icons/logo.svg" width="24" height="24" alt="">MarkVault</span><a class="btn btn-primary btn-small preview-new" href="#/app?add=1">${icon('plus')} New bookmark <kbd>N</kbd></a><div class="preview-nav"><span class="preview-nav-item active">${icon('bookmark')} All bookmarks <small>0</small></span><span class="preview-nav-item">${icon('inbox')} Unread <small>0</small></span><span class="preview-nav-item">${icon('star')} Favorites <small>0</small></span><span class="preview-nav-item">${icon('clock')} Recently added</span></div><div class="preview-folder-label">FOLDERS ${icon('plus')}</div><p class="preview-sidebar-hint">A place for every interest.</p><div class="preview-sidebar-bottom">${icon('shield')} Private by design ${icon('settings')}</div></aside><div class="preview-main"><div class="preview-topbar"><span>${icon('search')} Search your vault…</span><kbd>⌘ K</kbd></div><div class="preview-content"><div class="spread"><div><h4>All bookmarks <span class="count-badge">0</span></h4><p>Your internet, a little more intentional.</p></div><div class="preview-view">${icon('grid')}${icon('list')}</div></div><div class="preview-welcome"><div class="bookmark-art"><span class="art-sheet sheet-back"></span><span class="art-sheet sheet-middle"></span><span class="art-sheet sheet-front">${icon('bookmark')}<i></i><i></i><i></i></span><span class="art-plus">${icon('plus')}</span></div><h3>A fresh space for your next discovery.</h3><p>Good things deserve a place to stay.</p><a href="#/app?add=1" class="btn btn-primary btn-small">${icon('plus')} Save your first link</a><a class="preview-import" href="#/app?import=1">or import your bookmarks ${icon('arrow')}</a></div><div class="preview-bottom">${icon('lock')} Only on this device. Only for you.<span>Ready when you are.</span></div></div></div></div></div><div class="product-caption"><span>${icon('checkcircle')} Thoughtfully simple</span><span>${icon('bolt')} Effortlessly fast</span><span>${icon('shield')} Uncompromisingly private</span></div></div>
      </section>
      <mv-section id="features"><div class="section-heading-row"><div class="section-title"><span class="eyebrow">A place for your internet</span><h2>Less searching.<br>More discovering.</h2></div><p>For the article you’ll read later.<br>The tool you’ll need again.<br>The idea you don’t want to lose.</p></div><div class="bento-grid">${features.map(([symbol, title, body, type]) => html`<article class="feature-card feature-${type}"><span class="feature-icon">${icon(symbol)}</span><div class="feature-copy"><h3>${title}</h3><p>${body}</p></div>${type === 'organize' ? html`<div class="organization-visual"><div class="visual-folder">${icon('folder')} A place for every interest <span>+</span></div><div class="visual-branch"><span class="visual-line"></span><mv-tag-pill label="ideas"></mv-tag-pill><mv-tag-pill label="inspiration"></mv-tag-pill><mv-tag-pill label="read later"></mv-tag-pill></div><div class="abstract-card"><span class="abstract-monogram">${icon('link')}</span><div><i></i><i></i></div>${icon('bookmark')}</div><div class="abstract-card muted-card"><span class="abstract-monogram">${icon('globe')}</span><div><i></i><i></i></div>${icon('bookmark')}</div></div>` : type === 'find' ? html`<div class="search-visual">${icon('search')} <span>That thing you saved…</span><kbd>⌘ K</kbd></div>` : type === 'private' ? html`<div class="privacy-visual"><span>${icon('lock')}</span><i></i><span>${icon('bookmark')}</span></div><span class="visual-footnote">YOUR DEVICE. YOUR DATA.</span>` : type === 'keys' ? html`<div class="keys-visual"><kbd>⌘</kbd><kbd>K</kbd></div>` : type === 'portable' ? html`<div class="file-pills"><span>.html</span><span>.json</span><span>.csv</span>${icon('arrow')}</div>` : html`<div class="theme-visual"><div>${icon('moon')}<i></i><i></i></div><div>${icon('sun')}<i></i><i></i></div></div>`}</article>`)}</div></mv-section>
      <mv-section id="shortcuts" class="keyboard-section"><div class="section-title"><span class="eyebrow">Made for your momentum</span><h2>Think it.<br>Find it. Keep going.</h2><p>Less clicking, more doing. A keyboard-first experience that keeps up with the way you think.</p><button class="text-link" data-action="shortcuts">Explore all shortcuts ${icon('arrow')}</button><span class="keyboard-note">Works with ⌘ on Mac and Ctrl on Windows.</span></div><div class="keyboard-showcase"><div class="keyboard-showcase-top">${icon('keyboard')} A little muscle memory. A lot of time back.</div>${shortcuts.slice(0,6).map(s => html`<div class="shortcut-row"><span>${s.label}</span><kbd>${s.keys}</kbd></div>`)}<div class="keyboard-showcase-bottom">Built for the way you work.<span>Press <kbd>?</kbd> anytime</span></div></div></mv-section>
      <mv-section id="privacy"><div class="privacy-heading"><span class="eyebrow">Private isn't a setting. It's the foundation.</span><h2>Your bookmarks.<br>Not our business.</h2><p>No sign-up walls. No analytics watching your clicks.<br>Just a small, useful tool that stays out of your way.</p></div><div class="privacy-steps"><article><span class="step-number">01<span> / </span></span><h3>Right here. On your device.</h3><p>Your vault lives in your browser’s IndexedDB. Not in a cloud. Not on our servers. There aren’t any.</p></article><article><span class="step-number">02<span> / </span></span><h3>Nothing leaves. By default.</h3><p>No tracking scripts, no background requests. External previews are optional, and always your choice.</p></article><article><span class="step-number">03<span> / </span></span><h3>Take it with you. Anytime.</h3><p>Export a backup in one click. Open formats, no lock-in. Your collection stays yours for the long run.</p></article></div><div class="privacy-note">${icon('shield')} Local-first means you’re in control. Remember to back up the things you care about.<a href="#/docs?topic=backups">About backups ${icon('arrow')}</a></div></mv-section>
      <mv-section id="faq" class="faq-section"><div class="section-title"><span class="eyebrow">A few things to know</span><h2>Good questions.<br>Clear answers.</h2><p>A simple tool shouldn’t come with fine print.</p><a class="text-link" href="#/docs">Read the documentation ${icon('arrow')}</a></div><div class="faq-list">${faqs.map(([q,a]) => html`<details class="faq-item"><summary>${q}<span class="faq-plus">${icon('plus')}</span></summary><p>${a}</p></details>`)}</div></mv-section>
      <mv-section class="cta-section"><div class="final-cta"><span class="final-logo"><img src="assets/icons/logo.svg" width="48" height="48" alt=""></span><h2>A better home for your links.</h2><p>Your next great find deserves more than another open tab.</p><a class="btn btn-primary" href="#/app">Make space for what matters ${icon('arrow')}</a><span class="hero-micro">Free to use. Yours to keep.</span></div></mv-section>
    </main>
    <footer class="marketing-footer"><div class="footer-grid"><div class="footer-brand">${brand()}<p>Your links, finally organized.</p><div class="footer-chips"><span>Local-first</span><span>No account</span><span>No tracking</span></div></div>${[['Product',['Features','Shortcuts','Import','Export','Changelog']],['Resources',['Documentation','Keyboard reference','FAQ','GitHub']],['Privacy',['How your data is stored','Backups','Third-party requests']],['About',['Roadmap','License','Report an issue']]].map(([title,links]) => html`<div class="footer-column"><h4>${title}</h4>${links.map(label => html`<a href="${footerLink(label)}" target="${['GitHub','Report an issue','License'].includes(label)?'_blank':false}" rel="${['GitHub','Report an issue','License'].includes(label)?'noopener noreferrer':false}">${label}</a>`)}</div>`)}</div><div class="footer-bottom"><span>© ${new Date().getFullYear()} MarkVault. All Rights Reserved</span><a class="footer-source" href="${repository}" target="_blank" rel="noopener noreferrer">Open source. Made to be yours.</a></div></footer>
  `);
  const scrollTo = (id) => { if (signal.aborted) return; root.querySelector(`#${id}`)?.scrollIntoView({ behavior: document.documentElement.hasAttribute('data-reduced-motion') || matchMedia('(prefers-reduced-motion:reduce)').matches ? 'instant' : 'smooth' }); };
  root.addEventListener('click', event => { const link = event.target.closest('[data-section]'); if (link) { event.preventDefault(); scrollTo(link.dataset.section); } }, { signal });
  delegate(root, { theme: () => applyTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'), shortcuts: showShortcuts, menu: () => showMarketingMenu(scrollTo) }, signal);
  root.querySelectorAll('details').forEach(detail => detail.addEventListener('toggle', () => { if (detail.open) root.querySelectorAll('details').forEach(other => { if (other !== detail) other.open = false; }); }, { signal }));
  const nav = root.querySelector('.marketing-nav'); const sentinel = new IntersectionObserver(entries => nav.classList.toggle('scrolled', !entries[0].isIntersecting)); sentinel.observe(root.querySelector('.nav-sentinel'));
  const sections = new IntersectionObserver(entries => { entries.forEach(entry => { if (entry.isIntersecting) { root.querySelectorAll('.nav-links a').forEach(a => { const active = a.dataset.section === entry.target.id; if (active) a.setAttribute('aria-current','true'); else a.removeAttribute('aria-current'); }); } }); }, { rootMargin: '-20% 0px -50% 0px' }); root.querySelectorAll('mv-section[id]').forEach(el => sections.observe(el));
  if (new URLSearchParams(location.search).get('menu') === 'open') showMarketingMenu(scrollTo);
  const section = new URLSearchParams(location.search).get('section');
  if (section === 'footer') document.fonts.ready.then(() => { if (signal.aborted) return; const timer = setTimeout(() => { if (signal.aborted) return; window.scrollTo({ top:document.documentElement.scrollHeight, behavior:'instant' }); root.querySelector('.marketing-footer')?.setAttribute('data-review-ready','true'); }, 300); signal.addEventListener('abort', () => clearTimeout(timer), { once:true }); });
  return () => { sentinel.disconnect(); sections.disconnect(); };
}
