// @ts-check
import { html, delegate } from '../core/dom.js';
import { prefs, applyTheme } from '../core/store.js';
import { roving } from '../core/focus.js';
import { bytes, relativeTime } from '../core/format.js';
import { vault, clearVault } from '../services/vault.js';
import { exportVault } from '../services/export.js';
import { checkLinks } from '../services/linkcheck.js';
import { showImport, confirmAction } from '../components/dialogs.js';
import { toast } from '../components/primitives.js';
const icon = name => html`<mv-icon name="${name}"></mv-icon>`;
const tabs = [['appearance','Appearance'],['previews','Link previews'],['transfer','Import & export'],['backup','Backup & storage'],['danger','Danger zone']];
/** Mount settings with scoped listeners and roving keyboard navigation. @param {HTMLElement} slot @param {AbortSignal} signal */
export async function mountSettings(slot, signal) {
  slot.className = 'page-slot settings-layout';
  slot.append(html`<nav class="settings-tabs" role="tablist" aria-label="Settings categories"><!-- Static template comment, never user content -->${tabs.map(([id,label]) => html`<button class="settings-tab" role="tab" data-tab="${id}" id="tab-${id}" aria-controls="settings-panel" aria-selected="false" tabindex="-1">${label}</button>`)}</nav><section class="settings-panel" id="settings-panel" role="tabpanel"></section>`);
  let panelController, runController; const panel = slot.querySelector('.settings-panel');
  const mount = async tab => {
    panelController?.abort(); panelController = new AbortController(); const panelSignal = panelController.signal;
    slot.querySelectorAll('[role=tab]').forEach(button => { const selected = button.dataset.tab === tab; button.setAttribute('aria-selected', String(selected)); button.tabIndex = selected ? 0 : -1; });
    panel.setAttribute('aria-labelledby', `tab-${tab}`);
    if (tab === 'appearance') panel.replaceChildren(html`<h2>Make yourself at home.</h2><p>The same quiet workspace, in your own style.</p><div class="setting-row"><div><h3>Color theme</h3><p>Choose a mood, or follow your device.</p></div><select name="theme" aria-label="Color theme"><option value="dark">Dark</option><option value="light">Light</option><option value="system">System</option></select></div><div class="setting-row"><div><h3>Default view</h3><p>A visual collection or a focused list.</p></div><select name="view" aria-label="Default view"><option value="grid">Grid</option><option value="list">List</option><option value="compact">Compact</option></select></div><div class="setting-row"><div><h3>Default sort</h3><p>Put what matters first.</p></div><select name="sort" aria-label="Default sort"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="title">Title A–Z</option><option value="visited">Most visited</option></select></div><div class="setting-row"><div><h3>Reduce motion</h3><p>Keep transitions still. Your device preference is always respected.</p></div><input type="checkbox" name="reducedMotion" aria-label="Reduce motion"></div>`);
    if (tab === 'previews') panel.replaceChildren(html`<h2>Your privacy, your call.</h2><p>External requests are off by default. Enable only what you’re comfortable sharing.</p><div class="setting-row"><div><h3>Website favicons</h3><p>Fetch icons from Google. The domain of each displayed bookmark is sent to Google.</p></div><input type="checkbox" name="externalFavicons" aria-label="Enable external favicons"></div><div class="setting-row"><div><h3>Fetch link previews</h3><p>Send the full URL to the preview provider when adding or editing. Never required to save.</p></div><input type="checkbox" name="previews" aria-label="Enable link previews"></div><div class="setting-column"><label>Preview endpoint<input name="previewEndpoint" type="url" value="${prefs.state.previewEndpoint}"></label><p class="form-hint">The encoded bookmark URL is appended. The endpoint must be CORS-enabled and require no API key. Only titles and descriptions are cached locally.</p></div><div class="notice">${icon('shield')}<p>Turning previews off stops future requests. Existing bookmarks stay on your device. Provider availability and rate limits are outside MarkVault’s control.</p></div><div class="setting-row"><div><h3>Link health</h3><p>A manual check connects to each saved website. Browsers hide HTTP status codes, so only network failures can be reported.</p></div><button class="btn" data-action="check-links">Check links</button></div><div class="link-progress" hidden><progress class="progress" value="0" max="100"></progress><p class="form-hint" aria-live="polite"></p><button class="btn btn-small" data-action="cancel-check">Cancel check</button></div>`);
    if (tab === 'transfer') panel.replaceChildren(html`<h2>Come and go as you please.</h2><p>Open formats. No lock-in. Your bookmarks belong to you.</p><div class="setting-row"><div><h3>Import your collection</h3><p>Browser HTML, MarkVault JSON, or Raindrop / Pocket CSV. Preview first, then confirm.</p></div><button class="btn btn-primary" data-action="import">${icon('upload')} Import</button></div><div class="setting-row"><div><h3>Full-fidelity backup</h3><p>JSON preserves notes, tags, folders, visits, timestamps, and Trash.</p></div><button class="btn" data-action="export-json">${icon('download')} JSON</button></div><div class="setting-row"><div><h3>Back to your browser</h3><p>HTML with folder structure for Chrome, Firefox, Safari, or Edge.</p></div><button class="btn" data-action="export-html">${icon('download')} HTML</button></div><div class="setting-row"><div><h3>Spreadsheet-friendly</h3><p>Active links, titles, descriptions, tags, and creation dates.</p></div><button class="btn" data-action="export-csv">${icon('download')} CSV</button></div>`);
    if (tab === 'backup') {
      const last = vault.value.meta.find(m => m.key === 'lastBackupAt')?.value;
      panel.replaceChildren(html`<h2>A little backup. A lot of peace of mind.</h2><p>Local-first means you own your data — and your backups.</p><div class="setting-row"><div><h3>Save a full backup</h3><p>${last ? 'Last backup ' + relativeTime(last) : 'You haven’t exported a backup yet.'}</p></div><button class="btn btn-primary" data-action="export-json">${icon('download')} Export JSON</button></div><div class="setting-row"><div><h3>Browser storage</h3><p class="storage-estimate">Checking available storage…</p></div>${icon('vault')}</div><div class="setting-row"><div><h3>Persistent storage</h3><p>Ask the browser to retain your vault under storage pressure. Not a replacement for backups.</p></div><button class="btn" data-action="persist">Request</button></div><div class="notice">${icon('alert')}<p>Clearing site data or deleting this browser profile can remove your vault. A different site address has a different vault. Save JSON backups outside your browser.</p></div>`);
      try { const estimate = await navigator.storage?.estimate?.(); if (!panelSignal.aborted) panel.querySelector('.storage-estimate').textContent = estimate ? `${bytes(estimate.usage || 0)} used of ${bytes(estimate.quota || 0)} available to this site.` : 'Storage estimates are not supported in this browser.'; } catch { if (!panelSignal.aborted) panel.querySelector('.storage-estimate').textContent = 'Storage estimate is unavailable.'; }
    }
    if (tab === 'danger') panel.replaceChildren(html`<h2>A clean slate.</h2><p>Take a backup before making a change you can’t undo.</p><div class="setting-row"><div><h3>Clear this vault</h3><p>Permanently delete all bookmarks, folders, tags, and metadata in this browser.</p></div><button class="btn danger" data-action="clear">${icon('trash')} Clear vault</button></div><div class="notice">${icon('alert')}<p>This cannot be undone. You’ll need to type DELETE to confirm. Exported files and other devices are not affected.</p></div>`);
    if (panelSignal.aborted) return;
    panel.querySelectorAll('select,input[type=checkbox]').forEach(input => { if (input.type === 'checkbox') input.checked = !!prefs.state[input.name]; else input.value = prefs.state[input.name]; });
    panel.addEventListener('change', event => {
      const input = event.target; if (!input.name) return;
      if (input.name === 'previewEndpoint') { try { const url = new URL(input.value); if (!['http:', 'https:'].includes(url.protocol)) throw new Error(); prefs.state.previewEndpoint = input.value; toast('Preview endpoint saved.'); } catch { toast('Use a valid http or https endpoint.'); input.value = prefs.state.previewEndpoint; } return; }
      const value = input.type === 'checkbox' ? input.checked : input.value;
      if (input.name === 'theme') applyTheme(value); else prefs.state[input.name] = value;
      if (input.name === 'reducedMotion') document.documentElement.toggleAttribute('data-reduced-motion', value);
    }, { signal: panelSignal });
    const save = async format => { const saved = await exportVault(format); if (saved !== false) toast('Backup exported. Keep a copy somewhere safe.'); };
    delegate(panel, { import: showImport, 'export-json': () => save('json'), 'export-html': () => save('html'), 'export-csv': () => save('csv'), persist: async () => { const granted = await navigator.storage?.persist?.(); toast(granted ? 'Persistent storage granted. Keep making backups, too.' : 'Persistent storage was not granted. Regular exports are your best backup.'); }, clear: async () => { if (await confirmAction('Permanently clear this vault?', 'Every bookmark, folder, tag, and local metadata record will be removed. Export a backup first.', 'DELETE')) { await clearVault(); toast('Your vault has been cleared.'); location.hash = '/app'; } }, 'check-links': async () => {
      const links = vault.value.bookmarks.filter(b => !b.deletedAt); if (!links.length) return toast('Save bookmarks before checking links.');
      if (!await confirmAction('Connect to your saved websites?', `This check requests ${links.length} websites. Opaque responses cannot reveal HTTP errors; only network failures are detected.`)) return;
      runController?.abort(); runController = new AbortController(); panelSignal.addEventListener('abort', () => runController?.abort(), { once: true });
      const box = panel.querySelector('.link-progress'), button = panel.querySelector('[data-action="check-links"]'); box.hidden = false; button.disabled = true;
      try { await checkLinks(links, (done, total) => { box.querySelector('progress').value = done / total * 100; box.querySelector('p').textContent = `${done} of ${total} links checked. Network-level checks only.`; }, runController.signal); if (!panelSignal.aborted) box.querySelector('p').textContent = runController.signal.aborted ? 'Cancelled. Completed results are kept.' : 'Complete. See Unreachable for network failures.'; } finally { if (!panelSignal.aborted) button.disabled = false; }
    }, 'cancel-check': () => runController?.abort() }, panelSignal);
  };
  slot.querySelector('.settings-tabs').addEventListener('click', event => { const tab = event.target.closest('[data-tab]'); if (tab) mount(tab.dataset.tab); }, { signal });
  roving(slot.querySelector('.settings-tabs'), signal);
  const initial = new URLSearchParams(location.hash.split('?')[1]).get('tab'); await mount(tabs.some(t => t[0] === initial) ? initial : 'appearance');
  return () => { panelController?.abort(); runController?.abort(); };
}
