// @ts-check
import { html, delegate } from '../core/dom.js';
import { openDialog } from '../core/focus.js';
import { debounce } from '../core/scheduler.js';
import { normalizeUrl, prettifyTitle, domainOf, isValidUrl } from '../core/url.js';
import { shortcuts } from '../lib/constants.js';
import { vault, saveBookmark, createFolder, renameFolder, importVault, updateBookmarks } from '../services/vault.js';
import { parseImport } from '../services/import.js';
import { metadata } from '../services/metadata.js';
import { createShare } from '../services/share.js';
import { markdown } from '../services/markdown.js';
import { toast } from './primitives.js';
const icon = name => html`<mv-icon name="${name}"></mv-icon>`;
/** Shared native dialog surface with abortable lifecycle. @param {string} title @param {Node} content @param {string} className */
export function dialog(title, content, className = '') { const element = document.createElement('dialog'); element.className = `dialog ${className}`; const controller = new AbortController(); element.setAttribute('aria-labelledby','dialog-title'); element.append(html`<div class="dialog-header"><h2 id="dialog-title">${title}</h2><button class="icon-btn" data-action="close" aria-label="Close dialog">${icon('close')}</button></div>${content}`); delegate(element, { close: () => element.close() }, controller.signal); element.addEventListener('close', () => controller.abort(), { once:true }); openDialog(element); return { element, signal:controller.signal }; }
/** @param {string} title @param {string} message */
export function showInfo(title, message) { return dialog(title, html`<div class="dialog-body"><p>${message}</p></div><div class="dialog-footer"><button class="btn btn-primary" data-action="close">Got it</button></div>`); }
/** Show the shared, single-source keyboard reference. */
export function showShortcuts() { dialog('A shortcut to everything.', html`<div class="dialog-body"><p class="form-hint">Less reaching for your mouse. More staying in flow.</p><div>${shortcuts.map(s => html`<div class="shortcut-row"><span>${s.label}</span><kbd>${s.keys}</kbd></div>`)}</div><p class="form-hint">Use ⌘ on Mac or Ctrl on Windows and Linux. Shortcuts pause while you’re typing.</p></div>`); }
/** Confirmation with optional explicit text entry. @param {string} title @param {string} message @param {string} word @returns {Promise<boolean>} */
export function confirmAction(title, message, word = '') { return new Promise(resolve => { const { element, signal } = dialog(title, html`<div class="dialog-body"><p>${message}</p>${word ? html`<label>Type ${word} to confirm<input name="confirmation" autocomplete="off" placeholder="${word}"></label>` : ''}</div><div class="dialog-footer"><button class="btn" data-action="close">Cancel</button><button class="btn btn-primary" data-action="confirm" disabled="${word ? true : false}">Confirm</button></div>`); let confirmed = false; const button = element.querySelector('[data-action="confirm"]'); element.querySelector('input')?.addEventListener('input', e => { button.disabled = e.target.value !== word; }, { signal }); button.addEventListener('click', () => { confirmed = true; element.close(); }, { signal }); element.addEventListener('close', () => resolve(confirmed), { once:true }); }); }
/** Create or rename an empty folder. @param {object|null} existing @param {string|null} parentId */
export function showFolder(existing = null, parentId = null) { const { element, signal } = dialog(existing ? 'Rename folder' : 'A new place for your links', html`<form id="folder-form"><div class="dialog-body"><label>Folder name<input name="name" placeholder="Something you’re into" value="${existing?.name || ''}" maxlength="100" required autofocus></label><p class="form-hint">${existing ? 'Your bookmarks will stay right where they are.' : 'Start with an empty folder. Make it yours.'}</p><p class="form-error" hidden></p></div><div class="dialog-footer"><button type="button" class="btn" data-action="close">Cancel</button><button class="btn btn-primary" type="submit">${existing ? 'Save name' : 'Create folder'}</button></div></form>`); element.querySelector('form').addEventListener('submit', async event => { event.preventDefault(); try { const name = new FormData(event.target).get('name').toString(); if (existing) await renameFolder(existing.id,name); else await createFolder(name,parentId); element.close(); toast(existing ? 'Folder renamed.' : 'A new folder, ready for your ideas.'); } catch(error) { const box = element.querySelector('.form-error'); box.textContent = error.message; box.hidden = false; } }, { signal }); }
/** Add / edit bookmark dialog, with a metadata-rich detail-sheet option. @param {object|null} existing @param {object} options */
export function showBookmark(existing = null, options = {}) {
  const tags = existing ? vault.value.tags.filter(t => existing.tagIds.includes(t.id)).map(t => t.name).join(', ') : '';
  const { element, signal } = dialog(existing ? (options.detail ? 'Inside your bookmark' : 'Edit bookmark') : 'Keep something worth finding.', html`<form id="bookmark-form"><div class="dialog-body"><p class="form-hint">${existing ? 'A little context makes it easier to rediscover.' : 'A useful tool. A fresh idea. A good read. Give it a home.'}</p><label>Link<input name="url" type="text" inputmode="url" placeholder="https://something-worth-keeping.com" value="${existing?.url || ''}" required autofocus autocomplete="url"></label><div class="field-preview" hidden></div><p class="clipboard-hint form-hint" hidden>Pasted from clipboard</p><label>Title<input name="title" placeholder="Give this link a little context" value="${existing?.title || ''}" maxlength="500"></label><label>Description<input name="description" placeholder="What makes this worth saving?" value="${existing?.description || ''}" maxlength="2000"></label><div class="form-row"><label>Folder<select name="folderId"><option value="">No folder</option>${vault.value.folders.map(f => html`<option value="${f.id}" selected="${f.id === (existing?.folderId || options.folderId)}">${f.name}</option>`)}</select></label><label>Tags<input name="tags" placeholder="ideas, read later" value="${tags}"><span class="form-hint">Separate tags with commas.</span></label></div><label><span class="spread">A note to future you <button class="text-link" type="button" data-action="preview-note">Preview</button></span><textarea name="note" placeholder="Why you saved it. What to come back to. Markdown supported.">${existing?.note || ''}</textarea></label><div class="markdown-preview" hidden></div><div class="flex"><label class="check-label"><input type="checkbox" name="isFavorite" checked="${existing?.isFavorite}"> Add to favorites</label><label class="check-label"><input type="checkbox" name="isRead" checked="${existing?.isRead}"> Mark as read</label></div>${options.detail && existing ? html`<div class="notice">${icon('clock')}<span>Saved ${new Date(existing.createdAt).toLocaleDateString()} · ${existing.visitCount} visits${existing.lastVisitedAt ? ` · Last visited ${new Date(existing.lastVisitedAt).toLocaleDateString()}` : ''}</span></div>` : ''}<p class="form-error" role="alert" hidden></p></div><div class="dialog-footer">${existing ? html`<a class="btn btn-ghost" href="${existing.url}" target="_blank" rel="noopener noreferrer">Open link ${icon('external')}</a>` : ''}<button type="button" class="btn" data-action="close">Cancel</button><button type="submit" class="btn btn-primary">${existing ? 'Save changes' : 'Save bookmark'} ${icon('arrow')}</button></div></form>`, options.detail ? 'detail-sheet' : '');
  const form = element.querySelector('form'), urlInput = form.elements.namedItem('url'), titleInput = form.elements.namedItem('title'), errorBox = element.querySelector('.form-error'); let autoTitle = !existing; let revision = 0;
  titleInput.addEventListener('input', () => { autoTitle = false; }, { signal });
  const updatePreview = debounce(async () => { const run = ++revision; try { const normalized = normalizeUrl(urlInput.value); errorBox.hidden = true; const preview = element.querySelector('.field-preview'); preview.replaceChildren(html`<mv-favicon domain="${domainOf(normalized)}"></mv-favicon><div><span>${prettifyTitle(normalized)}</span><p>${normalized}</p></div>`); preview.hidden = false; if (autoTitle) titleInput.value = prettifyTitle(normalized); const duplicate = vault.value.bookmarks.find(b => b.normalizedUrl === normalized && b.id !== existing?.id); if (duplicate) { errorBox.textContent = `Already saved: “${duplicate.title}”${duplicate.deletedAt ? ' (in Trash)' : ''}. Edit the existing bookmark instead.`; errorBox.hidden = false; } const data = await metadata(normalized,signal); if (signal.aborted || run !== revision) return; if (data && autoTitle && data.title) titleInput.value = data.title; if (data?.description && !form.elements.namedItem('description').value) form.elements.namedItem('description').value = data.description; } catch { element.querySelector('.field-preview').hidden = true; } },400);
  urlInput.addEventListener('input',updatePreview,{ signal }); signal.addEventListener('abort',updatePreview.cancel,{ once:true });
  if (existing) updatePreview(); else (async () => { try { const permission = await navigator.permissions?.query({ name:'clipboard-read' }); if (permission?.state === 'granted' && !signal.aborted) { const text = await navigator.clipboard.readText(); if (!signal.aborted && !urlInput.value && isValidUrl(text)) { urlInput.value = text; element.querySelector('.clipboard-hint').hidden = false; updatePreview(); } } } catch {} })();
  delegate(element, { 'preview-note': () => { const preview = element.querySelector('.markdown-preview'); const textarea = form.elements.namedItem('note'); preview.hidden = !preview.hidden; textarea.hidden = !preview.hidden; preview.replaceChildren(markdown(textarea.value || 'Nothing here yet.')); element.querySelector('[data-action="preview-note"]').textContent = preview.hidden ? 'Preview' : 'Edit'; } }, signal);
  form.addEventListener('submit', async event => { event.preventDefault(); const button = form.querySelector('[type="submit"]'); button.disabled = true; errorBox.hidden = true; try { const values = Object.fromEntries(new FormData(form)); await saveBookmark({ ...(existing || {}), ...values, url: normalizeUrl(values.url), isFavorite: values.isFavorite === 'on', isRead: values.isRead === 'on' }, String(values.tags).split(',')); element.close(); toast(existing ? 'Bookmark updated.' : 'A good find, safely kept.'); } catch(error) { errorBox.textContent = error.message; errorBox.hidden = false; button.disabled = false; } }, { signal });
  return element;
}
/** Import with explicit parse/preview/confirm stages; no writes before confirmation. */
export function showImport() {
  const { element, signal } = dialog('Bring your internet with you.', html`<div class="dialog-body"><p class="form-hint">In your browser’s bookmark manager, choose <strong>Export bookmarks</strong>. Then drop that HTML file here. Works with Chrome, Firefox, Safari, and Edge.</p><label class="drop-zone">${icon('upload')}<strong>Drop your bookmarks here</strong><span class="form-hint">Browser HTML, MarkVault JSON, or CSV · up to 20 MB</span><input type="file" accept=".html,.htm,.json,.csv" aria-label="Choose a bookmark file"></label><div class="import-preview" hidden></div><p class="form-error" hidden role="alert"></p><progress class="progress" max="100" value="0" hidden></progress></div><div class="dialog-footer"><button class="btn" data-action="close">Cancel</button><button class="btn btn-primary" data-action="confirm-import" disabled>Choose a file first</button></div>`);
  let payload, loading = false; const button = element.querySelector('[data-action="confirm-import"]'), errorBox = element.querySelector('.form-error'), zone = element.querySelector('.drop-zone');
  const parse = async file => { if (!file || loading) return; loading = true; button.disabled = true; button.textContent = 'Reading your file…'; errorBox.hidden = true; try { payload = await parseImport(file,signal); if (signal.aborted) return; const seen = new Set(vault.value.bookmarks.map(b => b.normalizedUrl)); let duplicates = 0; payload.bookmarks.forEach(b => { if (seen.has(b.normalizedUrl)) duplicates++; else seen.add(b.normalizedUrl); }); const preview = element.querySelector('.import-preview'); preview.hidden = false; preview.replaceChildren(html`<div class="notice">${icon('checkcircle')}<span><strong>${payload.bookmarks.length} bookmarks · ${payload.folders.length} folders</strong><br>${duplicates} duplicates will be skipped${payload.invalid ? ` · ${payload.invalid} invalid links excluded` : ''}. Review before importing.</span></div><div class="table-scroll"><table class="preview-table"><thead><tr><th>Title</th><th>Domain</th></tr></thead><tbody>${payload.bookmarks.slice(0,30).map(b => html`<tr><td>${b.title}</td><td>${b.domain}</td></tr>`)}</tbody></table></div>${payload.bookmarks.length > 30 ? html`<p class="form-hint">Showing the first 30 bookmarks.</p>` : ''}`); button.disabled = payload.bookmarks.length === 0; button.textContent = `Import ${payload.bookmarks.length - duplicates} bookmarks`; } catch(error) { if (error.name !== 'AbortError') { errorBox.textContent = error.message; errorBox.hidden = false; button.textContent = 'Choose another file'; } } finally { loading = false; } };
  element.querySelector('input').addEventListener('change', e => parse(e.target.files[0]), { signal });
  ['dragenter','dragover'].forEach(type => zone.addEventListener(type,e => { e.preventDefault(); zone.classList.add('dragging'); },{ signal })); ['dragleave','drop'].forEach(type => zone.addEventListener(type,e => { e.preventDefault(); zone.classList.remove('dragging'); if (type === 'drop') parse(e.dataTransfer.files[0]); },{ signal }));
  button.addEventListener('click', async () => { if (!payload || loading) return; loading = true; button.disabled = true; button.textContent = 'Making room for your links…'; const progress = element.querySelector('progress'); progress.hidden = false; try { const result = await importVault(payload,(done,total) => progress.value = done / total * 100); element.close(); toast(`${result.imported} bookmarks imported. ${result.skipped} duplicates skipped.`); } catch(error) { errorBox.textContent = `${error.message} Already imported chunks remain safely saved. You can retry; duplicates will be skipped.`; errorBox.hidden = false; button.disabled = false; button.textContent = 'Retry import'; } finally { loading = false; } },{ signal });
}
/** Create an explicit, copyable read-only share URL. @param {Array} bookmarks */
export function showShare(bookmarks) { if (!bookmarks.length) return toast('Select at least one bookmark to share.'); const url = createShare(bookmarks); const { element, signal } = dialog('A good find is better shared.',html`<div class="dialog-body"><div class="notice">${icon('share')}<span>This link contains ${bookmarks.length} bookmarks. Anyone with it can read their URLs, titles, and descriptions. Private notes and visit history are not included.</span></div><label>Read-only share link<textarea readonly name="share-url">${url}</textarea></label><p class="form-hint">${url.length.toLocaleString()} characters${url.length > 2000 ? ' — This is a long link. Some chat apps may truncate it; consider sharing fewer bookmarks.' : ' · No upload or server needed.'}</p></div><div class="dialog-footer"><button class="btn" data-action="close">Done</button><button class="btn btn-primary" data-action="copy">${icon('share')} Copy link</button></div>`); delegate(element,{ copy:async () => { try { await navigator.clipboard.writeText(url); toast('Share link copied.'); } catch { const field = element.querySelector('textarea'); field.focus(); field.select(); toast('Select and copy the link with your keyboard.'); } } },signal); }
/** Keyboard command palette: commands and actual local bookmarks only. */
export function showPalette() { const { element, signal } = dialog('What would you like to find?', html`<input class="command-search" placeholder="Search bookmarks or type a command…" aria-label="Search commands and bookmarks" autofocus><div class="command-results" role="listbox" aria-label="Commands and bookmarks"></div><div class="dialog-footer"><span class="form-hint">↑ ↓ to navigate · Enter to choose · Esc to close</span></div>`, 'command-palette'); const commands = [{ title:'New bookmark',icon:'plus', run:()=>showBookmark() },{ title:'Import bookmarks',icon:'upload',run:showImport },{ title:'All bookmarks',icon:'bookmark',run:()=>location.hash='/app' },{ title:'Settings',icon:'settings',run:()=>location.hash='/app/settings' },{ title:'Your vault in numbers',icon:'stats',run:()=>location.hash='/app/stats' },{ title:'Keyboard shortcuts',icon:'keyboard',run:showShortcuts }]; const input = element.querySelector('input'), results = element.querySelector('.command-results'); let options = [];
  const render = () => { const q = input.value.toLowerCase(); options = [...commands.filter(c=>c.title.toLowerCase().includes(q)), ...vault.value.bookmarks.filter(b=>!b.deletedAt && `${b.title} ${b.url}`.toLowerCase().includes(q)).slice(0,20).map(b=>({ title:b.title, icon:'bookmark',domain:b.domain,run:()=>showBookmark(b,{detail:true}) }))]; results.replaceChildren(...options.map((c,i)=>html`<button class="command-item" role="option" aria-selected="false" data-index="${i}">${icon(c.icon)}<span>${c.title}</span><small>${c.domain || 'Command'}</small></button>`)); if (!options.length) results.append(html`<p class="dialog-body muted">No matches. Try a title, domain, or command.</p>`); };
  input.addEventListener('input',render,{signal}); results.addEventListener('click',e=>{const item=e.target.closest('[data-index]');if(item){element.close();options[Number(item.dataset.index)].run();}},{signal}); element.addEventListener('keydown',e=>{if(!['ArrowDown','ArrowUp','Enter'].includes(e.key))return; const items=[...results.querySelectorAll('button')];const index=items.indexOf(document.activeElement);if(e.key==='Enter'){if(index<0)items[0]?.click();return;}e.preventDefault();items[(index+(e.key==='ArrowDown'?1:-1)+items.length)%items.length]?.focus();},{signal}); render(); }
